### ISSUE TITLE
[Investigation] Bundle locale files + minimum viable NPM module

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#159]
We currently serve the various Tradeshift UI versions via script URLs "CDN" style. That's great for end users, because they are likely to fetch the script from cache instead of downloading it multiple times. For testing purposes, however, it's been requested that:

1. We should not load the localization bundles from across the internet unless there's a very good reason to. So we should investigate the overhead of bundling all the localizations into the main file and determine if there is still a good reason to keep them separate.

2. Instead of always loading the main file from a CDN address, We should attempt to (also) distribute Tradeshift UI via some kind of NPM module that can be bundled along with the other resources *at least for testing purposes* so that testing becomes easier and cooler somehow.

Part number two is tricky for various reasons, not least because the load order in a browserified bundle is not deterministic (or at least not predictable) so perhaps we can bundle this task with the long standing background-task: Support script `defer` attribute so that UI components can be initialized at a more or less random point in time while still working out for us in V4. In any case, we should never attempt to perform a full "module" rewrite of the entire Tradeshift UI code base because then we'll have the same problem (of unpredictable load order) multiplied indefinitely.

**Comment by sampi** [comment]
Fixed. Closing.
