### ISSUE TITLE
[SideBar] should reflex when inserted post init

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#174]
If you append a SideBar to the stage sometime *after* the page has been initialized (and because the layout of the SideBar is JavaScript-based in order to work in IE9), the SideBar should `reflex()` itself in order to lock the footer to the bottom of the screen. For now, you will have to reflex manually using a strange and undocumented API:
```JavaScript
ts.ui.get('html').reflex(); // crawl the document and call reflex() on all components
```
Also, while we're at it, we should make a shorthand method `ts.ui.reflex()` that calls the above code.

**Comment by wiredearp** [comment]
It was not possible to recreate the bug (observed in V4) by inserting the SideBar on a `setTimeout` but at least the SideBar now flexes every time it is inserted (instead of just the first time). This will in theory fix the problematic scenario that might have caused this, and which plays out in the following order:

1. `DOMContentLoaded` is called and the UI components initialize
2. Angular wakes up and parses the templates in DOM, then removes  them from the DOM
3. Angular realizes that these fragments should in fact be positioned in the DOM and puts them back
4. Reflex was not called because this is not the *first* time for the SideBar to appear in the DOM (it was instantiated already in step `1` above)

In case this does not fix the behavior in V4, at least it is now possible to call `ts.ui.reflex()` as a nice API to recalculate all javascript-based layout in the document, so perhaps @sqren can test if manual reflex is still needed; and if it is, call the nice API `ts.ui.reflex()` instead of the not so nice API `ts.ui.get('html').reflex()`

**Comment by sqren** [comment]
> so perhaps @sqren can test if manual reflex is still needed

I should test on 7.0.0 or the current version in master?

**Comment by wiredearp** [comment]
`7.0.0` (if you have time, since you already have a workaround in place)
