### ISSUE TITLE
[Footer] enhanced functionality

### ISSUE THREAD

**Issue by RafalRasztemborski** [Tradeshift/tradeshift-ui#184]
#### Description of feature
BUY has a request of implementing the status bar (bottom-bar) with the following design: 
![screen shot 2017-03-10 at 15 25 29](https://cloud.githubusercontent.com/assets/3731456/23798699/0cfbc80e-05a6-11e7-9f42-b48c1735b2d8.png)
The bottom bar should also support the buttons from the current top bar ( we need to move buttons from top bar to bottom bar) 

I can see there is already a very similar implementation : 
![screen shot 2017-03-10 at 15 42 40](https://cloud.githubusercontent.com/assets/3731456/23799319/65a1ae72-05a8-11e7-8df2-bf9ae78228ed.png)

If the current text from the right within the status bar could support the button with ts-icon it would almost seems as what we need. 

Please synch with Janne and @jerf

**Comment by RafalRasztemborski** [comment]
hey, what's the status on this task ?:)

**Comment by wiredearp** [comment]
@RafalRasztemborski At long last, something similar to this was just released over on http://ui.tradeshift.com/#components/footer/index.html. The "Share This With a Colleague" is however now called"Collaborate On This" and as yet in English only, unfortunately.
