### ISSUE TITLE
[Forms] native select menu appears in iOS

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#215]
The `select` native dropdown menu appears in iOS (again 😞)

#### Tradeshift UI version affected
v7.1.0

#### Expected Behavior
Only our Aside menu should appear.

#### Actual Behavior
They both appear - the native select menu and the Aside menu.

#### Steps to reproduce
Click some `select` on your iPad running latest iOS version.

**Comment by sampi** [comment]
Fixed in iOS 11, but still broken in 10.

**Comment by sampi** [comment]
The `FakeSelectInput` gets the focus now, instead of the native select menu.
It only happens in iOS 10, doesn't seem to be an issues on iOS 11.

**Comment by DocGroth** [comment]
Not an issue anymore
