### ISSUE TITLE
[Forms] Taglibs found in the field stopped working

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#219]
@sampi and @zdlm 

#### Tradeshift UI version affected
v7.1.0

#### Expected Behavior
The `form-field` directive should magically expand the following markup into canonical Forms markup.

```html
<form data-ts="Form">
      <input form-field type="text" ng-value='ctrl1.getValue()' />
      <input form-field type="text" ng-value='ctrl1.getValue()' />
      <input form-field type="text" ng-value='ctrl1.getValue()' />
      <input form-field type="text" ng-value='ctrl1.getValue()' />
</form>
```
#### Actual Behavior
It almost works, but the `input` elements get the wrong component associated, well except for the first one.

#### But why?
It's because of this channeling in the FormsModule `['.ts-form input + input', ts.ui.Spirit]` which assumes that the canonical markup has been hardcoded.

#### Workaround
Place an empty `del` element between each and every `input` and promise to delete them when we issue a fix.

**Comment by sampi** [comment]
The `form-field` directive is non-standard so we should work together with @akarnachuk so they are alerted about form-related changes and keep the directives up-to-date.

Another option could be to change the directive to run on something other than an `<input />`, such as `<form-field />`, but this is a more counterintuitive change.

**Comment by wiredearp** [comment]
But if the tag is anything but the `<input>` itself, then there is no obvious place to declare the directives (for validation and what not) that should go onto the `input` except for this tag (say `field-field`) and then you would have to add business logic for transferring those directives to the `input` (and make sure they are never evaluated while they are on the wrong tag, since that might fail), so that could be an uphill battle. I agree that it's strange to have a tag that transforms the DOM of the surrounding environment instead of the descendant subtree, of course :disappointed:

**Comment by sampi** [comment]
Seems to be fixed on the other end, and it's a corner case. Closing.
