### ISSUE TITLE
right padding on inputs

### ISSUE THREAD

**Issue by tstapleton** [Tradeshift/tradeshift-ui#226]
long content in an `input` shows padding on the left side but not the right side.

and if we right align an `input type="number"`, then it comes right up against the border.

![screen shot 2017-04-05 at 3 00 19 pm](https://cloud.githubusercontent.com/assets/1149400/24728884/b54ff858-1a10-11e7-82a1-c3823c6e40bb.png)

**Comment by sampi** [comment]
Fixed. Closing.
