### ISSUE TITLE
[Icons] Add/Plus icon is not aligned in the center

### ISSUE THREAD

**Issue by liufuyang** [Tradeshift/tradeshift-ui#227]
#### Tradeshift UI version affected
v7.0.0

#### Expected Behavior
Icon in the middle

#### Actual Behavior
Icon a bit on the right

#### Screenshots (optional)
![image](https://cloud.githubusercontent.com/assets/161689/24796554/a4bcf5da-1b8d-11e7-8a25-67b38d289542.png)
![image](https://cloud.githubusercontent.com/assets/161689/24796561/b1879982-1b8d-11e7-9e3b-fe3cd3f30d99.png)

I think we should remove that `left: 1px` attribute

**Comment by liufuyang** [comment]
Tried to make a PR from fork but build filed... 
Will just leave this to your guys then as I don't have push access to the repo directly

**Comment by sampi** [comment]
Fixed. Closing.
