### ISSUE TITLE
[Forms] Form fields preview state

### ISSUE THREAD

**Issue by JaneBrink** [Tradeshift/tradeshift-ui#230]
#### Description of feature
Form field preview. The form field border disappears and the content stays where it is.

#### Example use cases and/or Prototype links
The new purchase request will be built from the new form fields. Because the Purchase request needs to support multiple use cases as well as different states and different role-based views. We are in an urgent need of the form field preview state. See use case example below
![2017 04 11 form preview mode ticket](https://cloud.githubusercontent.com/assets/16757168/24909574/c1e2b52a-1ec4-11e7-9ab6-2ceef00654e5.png)

#### Designs and/or Prototype screenshots
From Lloyds UI form field handover: 
![screen shot 2017-04-11 at 14 24 56](https://cloud.githubusercontent.com/assets/16757168/24909104/da0fcb12-1ec2-11e7-8413-269fc2d662a2.png)

**Comment by sampi** [comment]
This will probably be achieved with a classname or an attribute on the form field.
It's not very semantic, but I understand the need. We'll make sure to talk about it on our next planning meeting.
