### ISSUE TITLE
<a data-ts="Button"> has 100% width

### ISSUE THREAD

**Issue by ehats** [Tradeshift/tradeshift-ui#236]
### Bug report
I was trying to create an `<a>` that looks like a TS button. I was suggested to use

```
<a data-ts="Button" class="ts-tertiary">
	<span>Text</span>
</a>
```

But that causes the buttons to have 100% width (see screenshot).

A workaround is to create an ordinary button and wrap it in an `<a>` tag.

Tested on Firefox 53 (Linux)

#### Tradeshift UI version affected
v7.1.0

#### Expected Behavior

The buttons will show up as usual

#### Actual Behavior

The buttons show up with 100% width and their edges in the wrong place

#### Screenshots (optional)

![image](https://cloud.githubusercontent.com/assets/12268788/25375027/bf3b036e-299f-11e7-9abb-6ca820c24c46.png)

**Comment by sampi** [comment]
have you tried putting the fake 'button' inside a `Buttons` container?
http://ui.tradeshift.com/#components/buttons/buttons.html
something like:
```
<menu data-ts="Buttons">
	<li>
		<a data-ts="Button" class="ts-button">
			<span>Button One</span>
		</a>
	</li>
	<li>
		<a data-ts="Button" class="ts-button">
			<span>Button Two</span>
		</a>
	</li>
</menu>
```

**Comment by sampi** [comment]
in any case, we'll look into it, but this is a lower priority, because buttons should be buttons and links should be links, but in theory we shouldn't care about the tag being used.

**Comment by ehats** [comment]
@sampi I tried the container. The buttons' edges are now in the right place, but the button is still 100% wide.
