### ISSUE TITLE
ts.ui.Note with button is too big

### ISSUE THREAD

**Issue by Leonid-Yeromin** [Tradeshift/tradeshift-ui#237]
#### Tradeshift UI version affected
v7.1.0

![screen shot 2017-04-25 at 14 54 59](https://cloud.githubusercontent.com/assets/22071306/25386296/349a3612-29c7-11e7-82f6-6317ecb37dbc.png)

**Comment by wiredearp** [comment]
I think I made a bypass fix for this over on my branch, whatever I was working on before I went on vacation, I guess it was the `jmo/modal` branch.

**Comment by sampi** [comment]
@wiredearp There's no more `jmo/modal` branch, can you push it somewhere?
Otherwise I can do the fix, it's a simple cut & paste in the `.tsml` of the `Note`.

**Comment by wiredearp** [comment]
Well. It was merged to master, then.

**Comment by sampi** [comment]
I just realized my mistake, I'll start the release process of 7.2.0 to fix the issue.
