### ISSUE TITLE
[Aside] Aside.onclose() should cancel on return false

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#255]
@sampi @zdlm @wejendorp 

And the same goes for Notificatons and Dialogs and the SideBar in mobile breakpoint and I guess the DatePicker and the standard `select` picker and what not: It is a pattern that the Flux/Redux store can be the single source of truth for UI state and thus the automatic closing of components can be considered an illegal mutation of state; this would happen onclick the closing X, onclick the aside cover and onkeypress ESCAPE.

This should already be possible according to https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/core/core-gui%40tradeshift.com/spirits/asides/ts.ui.SideShowSpirit.js#L633 and https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/core/core-gui%40tradeshift.com/spirits/asides/ts.ui.AsideSpirit.js#L393, but apparently this doesn't really work so great, because the general UI (and the cover in particular) is not aware of the return value.

**Comment by wejendorp** [comment]
Nice summary, I have no more to add. Let me know when there's anything to test.
