### ISSUE TITLE
Table editor allows to execute javascript in FF

### ISSUE THREAD

**Issue by akarnachuk** [Tradeshift/tradeshift-ui#273]
### Bug report
Table editor allows to execute javascript code. When I paste the following code
>`</textarea><svg/onload="alert('Qasuar')">`

into table editor and press `enter` I'm getting alert.
(see https://tradeshift.atlassian.net/browse/HACK-273)

#### Tradeshift UI version affected
v8.0.2

#### Expected Behavior
No javascript should be executed

#### Actual Behavior
Javascript is allowed to be executed

#### Steps to reproduce
This was reproduced on Firefox 53.0.2 (64-bit)
and not reproduces in Chrome.

#### Screenshots (optional)
![image](https://cloud.githubusercontent.com/assets/14124825/26351810/4ce673ca-3fe3-11e7-92f3-b3140f490864.png)

**Comment by wiredearp** [comment]
:beer: Good find! Thanks for reporting.
