### ISSUE TITLE
[Switch] Switch component trigger the click event twice

### ISSUE THREAD

**Issue by rafalages** [Tradeshift/tradeshift-ui#283]
#### Tradeshift UI version affected
v8.0.3 and 7.x

#### Expected Behavior
Trigger one event

#### Actual Behavior
Trigger the event twice

#### Steps to reproduce
go to http://ui.tradeshift.com/#components/forms/
and attach a event listener on the switch component by pasting it in your console
`document.querySelector('iframe')[0].contentDocument.querySelector('.ts-fieldlabel.ts-switchlabel').addEventListener('click', (e)=> console.log(e.target))`

**Comment by sampi** [comment]
It's possible to get which element was clicked using `e.target` as you pointed out.

We can't know for sure if devs are listening for their clicks on the `input` or the `label` anymore, so it would be risky to remove either.

Closing.
