### ISSUE TITLE
Ability to define a static number of items per page in table component

### ISSUE THREAD

**Issue by lloydhumphreys** [Tradeshift/tradeshift-ui#297]
#### Description of feature
It would appear that the current table will load as many lines as will fit in the viewport.

DUI would appreciate a property that allows us to set a static number of lines per page. This is so that we can be sure to bounce the user back to the correct page when they hit back, and make sharing the table easier.

We would _love_ it if this could be done early in D3 so we can have it when we are building the new Document Manager :-)

**Comment by wiredearp** [comment]
The behavior you describe is not default, it is enabled by calling `table.maximize()`. If you don't call this method, the table defaults to setting a static number of rows per page as specified by the `max` and `size` methods (see http://ui.tradeshift.com/#components/table/paging.html). Let us know if you can manage to style this to still appear "maximized" (assuming that this is still desired).

**Comment by lloydhumphreys** [comment]
Ah, I missed that. Thank you!
