### ISSUE TITLE
[UITable] Sorting issue

### ISSUE THREAD

**Issue by george-iuriet** [Tradeshift/tradeshift-ui#301]
#### Tradeshift UI version affected
v8.1.6

Table sorting fails with `Uncaught Error: Expected all columns cells to have a value or text` if rows' cells are populated with strings, rather than objects. A workaround to it is to visit all the pages and then perform the sorting. 

Populating the cells like this fails: 

```
 "cells": [
      ...
      "CODING"
  ]
```

Populating the cells like this works:

```
"cells": [
      ...
      { text: "CODING", value: "CODING" }
]

```

**Comment by sampi** [comment]
Can't be reproduced. Closing.
