### ISSUE TITLE
[Modal]  Add option for transparent background

### ISSUE THREAD

**Issue by paulswebapps** [Tradeshift/tradeshift-ui#305]
#### Description of feature

On the [Modal component](http://ui.tradeshift.com/#components/modals/), add an option to apply the dark-transparent background, just like the [Dialog component](http://ui.tradeshift.com/#components/dialogs/).

#### Example use case

One idea is to add a class called `ts-transparent`, which could be applied like so:

```
<dialog data-ts="Modal" class="ts-transparent">
  <div data-ts="Panel">
    <p>Modal content.</p>
  </div>
</dialog>
```

#### Design screenshot

This is the design for the modal that I was tasked to implement:
<img width="1071" alt="confirm-modal" src="https://user-images.githubusercontent.com/913826/27444543-8b02fdf4-572b-11e7-89f1-aeead7289d50.png">

**Comment by bomouridsen** [comment]
@paulswebapps This is not the use-case we want for our Modal. This is a Dialog, so please use our very component Dialog component. It has support for Markdown and can achieve your desired design functionality.

Made a quick example below:
`ts.ui.Dialog.confirm('## Headline\n*Line One\n*Line Two\n### Terms\nText (Link)[https://www.tradeshift.com] Text', 'Accept', {
	icon: 'ts-icon-warning',
primary: 'accept',
	focused: 'accept'
});`

![image](https://user-images.githubusercontent.com/24455813/27585341-24828ec2-5b3c-11e7-84ec-233b92b9ec0d.png)

**Comment by paulswebapps** [comment]
Dialog does not allow you to put text under the buttons, per design
requirements. It also does not support all of the markdown I such a way to
fulfill design requirements (links and lists are broken).

**Comment by bomouridsen** [comment]
@paulswebapps 
> Dialog does not allow you to put text under the buttons, per design
requirements.

That is true, but it's not necessary for the users understanding of the dialog. If it's still an issue, please have the project designer contact me.

> links and lists are broken

Can you clarify?

**Comment by paulswebapps** [comment]
Since the example code is missing from the markdown documentation, I might
have done something wrong, but it failed to format markdown if I had both
links and a list in the same string. I'm at the airport, but could provide
example code later if more clarification is needed.

**Comment by sampi** [comment]
We know about this issue: https://github.com/Tradeshift/tradeshift-ui/issues/309 but otherwise, the code example (from the second comment) works perfectly.

**Comment by paulswebapps** [comment]
Thanks for taking the time to help me out. I tried the dialog component, and the code provided works. Unfortunately, because the dialog box is not wide enough, the lines are breaking in unpleasant spots. Also, if I place space or line-break after a markdown link, it is ignored, which increases the ugliness.

FYI: we currently have other teams creating their own one-off versions of the Modal component, to implement the transparent background (since they also need confirmation windows which are wider and more flexible than the Dialog component). So as a result, we are increasing the spread of custom implementations.

I know you all are busy, and overall the library works beautifully. Just wanted create awareness that this feature request would solve a problem for multiple teams.

**Comment by paulswebapps** [comment]
One more issue I forgot to mention: as you add more copy to the Dialog, its centering moves closer to the bottom of the page. To make it worse, if the buttons get pushed off-screen, there is no way to scroll to them. And since the dialog box stays skinny even on a large screen, the copy takes up more vertical space than normally would be necessary.

<img width="1014" alt="screen shot 2017-07-05 at 1 56 33 pm" src="https://user-images.githubusercontent.com/913826/27884894-bc8db29c-618a-11e7-804b-ae301b950580.png">

Supporting the use-case of the "modal" as a complex confirmation window, would not only solve our problem, but would also put our UI library more in-line with the industry standard terminology:

> In user interface design for computer applications, a modal window is a graphical control element subordinate to an application's main window. It creates a mode that disables the main window, but keeps it visible with the modal window as a child window in front of it.

https://en.wikipedia.org/wiki/Modal_window

Our Modal currently does not "keep the main window visible", and therefore does not fit the definition, which is more closely fits the Dialog.

Another option could be to modify the Dialog to support more complex layouts. Either way, we're going to see a spread of one-off implementations until something is done about these issues. I assume we're on the same page in wanting to avoid that.
