### ISSUE TITLE
You are stuck after searching on a mobile

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/tradeshift-ui#313]
#### Tradeshift UI version affected
v8.1.7

#### Expected Behavior
On an mobile phone, after searching you press the search result you want to load, and the page is loaded and the menu should disappear. 

#### Actual Behavior
On an mobile phone, after searching you press the search result you want to load, and the menu stays and you cant see the content. You can't close it on the x button either.

#### Steps to reproduce
I tested it on a iPhone SE and One+ 3T. 
Search for something, press the result

**Comment by sampi** [comment]
It's possible to exit now, but the page stayed zoomed in on iOS.

**Comment by sampi** [comment]
Made a new issue. https://github.com/Tradeshift/tradeshift-ui/issues/631
