### ISSUE TITLE
Adding custom classes to toolbar buttons prevents compact()

### ISSUE THREAD

**Issue by akarnachuk** [Tradeshift/tradeshift-ui#333]
### Bug report
Adding custom classes to toolbar buttons prevents compact()
I've modified example and added `tst-button-1` and `tst-button-2` classes to ts-tertiary buttons.

#### Tradeshift UI version affected
v8.2.1

#### Expected Behavior
When there are more then three toolbar buttons, tertiary buttons would be shown compactly - inside the menu.

#### Actual Behavior
All the buttons are shown at toolbar without compacting.

#### Steps to reproduce
Use example from http://ui.tradeshift.com/#components/bars/toolbar.html to `run this code`
```javascript
ts.ui.ToolBar.buttons([
	{label : 'Primary', type : 'ts-primary'},
	{label : 'Secondary', type : 'ts-secondary'},
	{label : 'Tertiary One', type : 'ts-tertiary tst-button-1'},
	{label : 'Tertiary Two', type : 'ts-tertiary tst-button-2'}
]);
```

**Comment by wiredearp** [comment]
:see_no_evil: Doh!
