### ISSUE TITLE
[Header] Implement the Header API

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#347]
### Feature request

This is a tracking bug for The New Header which shall deprecate the following APIs:

* `ts.ui.TopBar`
* `ts.ui.TabBar`
* `ts.ui.ToolBar`

This will also eradicate all second level navigation (via `ts.ui.TabBar.tabs()`) on the human interface level, so an unknown number of apps will need to be redesigned :eyes:

Depends on #349 - New TabBox component

**Comment by bomouridsen** [comment]
Hoping you're not doing any major sweeping change that will affect design before this idea has been presented to the design team. This is a big change and we need to do our home work first.
Changing the styling of current ts.ui.Tabbar is was has been approved and has priority. So will start with that.

**Comment by wiredearp** [comment]
It's not my idea, remember.

**Comment by lloydhumphreys** [comment]
Let's document some examples of a TabBar and how we'll migrate it into a Header.

Let's link these from the Docs pages.
