### ISSUE TITLE
[SideBar] SideBar component doesn't close on desktop

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/tradeshift-ui#371]
#### Tradeshift UI version affected
v9.1.1

#### Expected Behavior
SideBar component should close on desktop, not only on mobile.
#### Actual Behavior
SideBar component doesn't close on desktop.
#### Steps to reproduce
- try to close the SideBar component on desktop. This functionality works only on mobile. 
#### Screenshots (optional)
![bug_sidebar](https://user-images.githubusercontent.com/28289435/30015561-e6576cea-9159-11e7-8a3b-790b5d0e616d.png)

**Comment by wiredearp** [comment]
I don't think anyone ever attempted to do this before, but it was supposed to work like suggested, so I'll mark it as a `bug`.

**Comment by wiredearp** [comment]
It's challenging to make this consistent with the regular Aside API because the `open` property has been misused to deal with SideBars behavior in the mobile breakpoint (only). I suggest we postpone this enhancement until we have launched a number of other breaking changes in the near future. The workaround for now is to remove the SideBar from the DOM if and when it should not be visible.

**Comment by wiredearp** [comment]
Note to self: When we look at this issue, we should also release the following breaking change: The SideBar should hide itself in tablet portrait mode, just as it does in the mobile breakpoint. The app(s) will need to account for this. Also: We should consider if the "Show Hidden SideBar" action should be injected by default into the Header or Footer unless a "we-will-handle-this" attribute has been declared.

**Comment by wiredearp** [comment]
Let's try to fix this with an alternative `hide` and `show` API that can leave `open` and `close` to the mobile scenario.

**Comment by zdlm** [comment]
I don't think we need to fix it. The sidebar only can be hide and show in mobile. Like our documentation say here http://ui.tradeshift.com/v11/#components/sidebars/.
