### ISSUE TITLE
Close icon in note should be "brown"

### ISSUE THREAD

**Issue by jerf** [Tradeshift/tradeshift-ui#376]
#### Tradeshift UI version affected

Latest

#### Expected Behavior

The close button on the closeable note should be in the same brown color as the text in the note.

#### Actual Behavior

The close icon is blue.

#### Steps to reproduce

Visit: [http://ui.tradeshift.com/#components/notes/](http://ui.tradeshift.com/#components/notes/) and run the code in the first example.

**Comment by DocGroth** [comment]
Will happen with new colors
