### ISSUE TITLE
Table spinner cover remains after loading finished in IE11

### ISSUE THREAD

**Issue by upphiminn** [Tradeshift/tradeshift-ui#389]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
#### Tradeshift UI version affected
v9.2.0

#### Expected Behavior
Should not keep table cover after loading is done.
#### Actual Behavior
Keeps table white cover after loading is finished.
#### Steps to reproduce
Open `ui-dev.tradeshift.com` using IE11, spinner examples, table spinner section.
#### Screenshots (optional)
<img width="1552" alt="screen shot 2017-09-18 at 14 17 49" src="https://user-images.githubusercontent.com/820822/30541631-8a4c32c2-9c7c-11e7-9951-f6c41289cfe1.png">

---------------------------

**Comment by ricardoparro** [comment]
@DocGroth is it possible to give priority to this bug? This is affecting Unilever on the BSD Buyer App. Pls let me know.
