### ISSUE TITLE
[gui.Client] Add exception to accept 0px as a valid value on OSX

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#390]
@wiredearp @zdlm @GeorgeIuriet 

Should go here: https://github.com/Tradeshift/tradeshift-ui/blob/c95432a961ec40565f6257c0703c74b4e223288f/src/spiritual/spiritual-gui/gui%40wunderbyte.com/utils/gui.Client.js#L329

**Comment by wiredearp** [comment]
Since Tradeshift UI is out of the chrome, we can just rollback the changes to `gui.Client.js` :tada:
