### ISSUE TITLE
[Responsive Design] ts-hide-mobile-only is broken

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#394]
ClassName 'ts-hide-mobile-only' does not work in latest TSUI version

TSUI v9.2.3 (works in 9.1.1)

May be reproduced on JSFiddle:
https://jsfiddle.net/bhxqth9h/

Or just navigate to ui.ts.com:
http://ui.tradeshift.com/#appendix/responsive/

**Comment by wiredearp** [comment]
@n-srg Can you say if it has ever
