### ISSUE TITLE
[Spirits] Defensive strategy against hostile frameworks setting the `className` property

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#402]
It appears that React will do just that: Instead of updating CSS classnames via `elm.classList.add` and `remove`, it simply sets the full `className` to be whatever is declared in the JSX and/or Virtual DOM, at least when the amount of classnames changes from zero to one. Other frameworks could of course also assume to own all the classnames, so we should probably:

1. Add the `className` property to the `DOMCombos so` that we get notified whenever this prop changes.
2. Add business logic to the `setAttribute` combo so that the `class` atttribute also triggers a notification.
3. Make the `CSSPlugin` persist all classnames in a cache that can be compared with the DOM (whenever we get notified) to restore any missing classes.

**Comment by ciprianpratiats** [comment]
Regarding this, I also stumbled upon layout problems when i try to add the ts-error class to a date field:
before:
![dates_before](https://user-images.githubusercontent.com/28808432/30697135-993c8dec-9ee6-11e7-9fc7-6373d2b54eaf.png)
```<label class="ts-label ts-spirit ts-engine-webkit ts-haslabel ts-fieldlabel ts-textlabel ts-fakelabel ts-datelabel" data-ts-spirit="ts.ui.LabelSpirit"><span data-ts-spirit="ts.ui.LabelTextSpirit">From</span><input type="date" name="from" value="2016-09-21" data-ts-spirit="ts.ui.DateInputSpirit" class="ts-dateinput ts-spirit ts-field" spellcheck="false" autocomplete="off"><input data-ts-spirit="ts.ui.FakeDateInputSpirit" class="ts-fakedateinput ts-input ts-spirit ts-fake ts-field ts-text ts-date" tabindex="-1" type="text" name="" readonly="" spellcheck="false" autocomplete="off"></label>```

after:
![dates_error](https://user-images.githubusercontent.com/28808432/30697151-a6f9e61e-9ee6-11e7-8985-2dbd2d6e85b2.png)
```<label class="ts-error ts-fieldlabel ts-textlabel ts-fakelabel ts-datelabel" data-ts-spirit="ts.ui.LabelSpirit" id=""><span data-ts-spirit="ts.ui.LabelTextSpirit">From</span><input type="date" name="from" value="2017-09-30" data-ts-spirit="ts.ui.DateInputSpirit" class="ts-dateinput ts-spirit ts-field" spellcheck="false" autocomplete="off"><input data-ts-spirit="ts.ui.FakeDateInputSpirit" class="ts-fakedateinput ts-input ts-spirit ts-fake ts-field ts-text ts-date" tabindex="-1" type="text" name="" readonly="" spellcheck="false" autocomplete="off"></label>```

The actual code from the React componenet that displays this is:

```render() {
		const buttonGroupClass = classNames({
			'ts-t-t ts-join': !_.isEmpty(this.filterData)
		});
		const errorClass = classNames({
			'ts-error': !!this.state.error
		});

		return (
			<div>
				<form data-ts="Form" name={this.props.filterId}>
					<fieldset key="date-from" className="ts-layout-1-1">
						<label className={errorClass}>
							<span>
								{t('From')}
							</span>
							<input
								type="date"
								name="from"
								value={this.state.filterData.from}
								onChange={ev => this.setDate({ from: ev.target.value })}
							/>
						</label>
					</fieldset>
					<fieldset key="date-to" className="ts-layout-1-1">
						<label className={errorClass}>
							<span>
								{t('To')}
							</span>
							<input
								type="date"
								name="to"
								value={this.state.filterData.to}
								onChange={ev => this.setDate({ to: ev.target.value })}
							/>
						</label>
					</fieldset>
					{this.errorMessage()}
				</form>
				<menu data-ts="Menu" key="options">
					{_.map(dateOptions, (option, key) => this.menuItem(option, key))}
				</menu>
				<menu data-ts="Buttons" key="actions" className={buttonGroupClass}>
					<li>
						<button className="ts-primary applyFilter" onClick={this.applyFilter}>
							<span>
								{t('Apply filter')}
							</span>
						</button>
					</li>
					{this.deleteFiltersButton()}
				</menu>
			</div>
		);
	}```

**Comment by n-srg** [comment]
I facing this behavior as well as @ciprianpratiats. 
 the problem comes while I want to handle `ts-error` class for any input field on the form. React just erases input's class ' ts-haslabel ', And filed looks broken. All as said above.

As workaround, I force insert `ts-haslabel` class.
Example:
`		const keyClasses = classNames('ts-haslabel', {
			'ts-error': isKeyNonUniq
		});`

:disappointed:

**Comment by n-srg** [comment]
BTW I facing something really same for button with ` className="ts-danger"`
After render I see `class="ts-danger" ` instead of `class="ts-danger ts-button ts-spirit ts-ready" ` and button looks broken

**Comment by wiredearp** [comment]
Just to make sure it is the same issue, @n-srg, can you check if it works when you add a default classname such as `className='Johnson'` in your JSX? Alternatively, can you confirm that the button renders with the weird attribute `data-ts-spirit="ts.ui.ButtonSpirit"` in the final output? Thanks!

**Comment by n-srg** [comment]
yea I can confirm it contains spiritattribute `<button data-ts="Button" class="ts-danger" data-ts-spirit="ts.ui.ButtonSpirit" type="button"><span data-ts-spirit="ts.ui.LabelTextSpirit">Remove</span></button>`
