### ISSUE TITLE
[Pagination] Sometimes the last page number visible isn't displayed correctly

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/tradeshift-ui#410]
### Bug report
Sometimes the last page number visible (e.g. page 5) isn't displayed correctly. 

#### Tradeshift UI version affected
v9.2.4

#### Expected Behavior
The last page number visible should be displayed only number and `…`.

#### Actual Behavior
Sometimes the last page number visible (e.g. page 5) isn't displayed correctly (e.g. number 5 and `…`). It has some characters added extra near the page number instead of `…`.

#### Steps to reproduce
Display pagination component with totalPages greater than 5 (see the attachment file).

#### Screenshots (optional)
![bug_pagination](https://user-images.githubusercontent.com/28289435/31380471-27c82940-adba-11e7-8ade-8cec501148c6.png)

**Comment by DocGroth** [comment]
Fixed with https://github.com/Tradeshift/tradeshift-ui/issues/602
