### ISSUE TITLE
[Identity] White everything

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#422]
Let's remove all the background colors to create a nice and white baseline for the new visual identity.

- [x] Header
- [x] Bars (inline)
- [x] Aside
- [x] Modal
- [x] Table (mihnea.zamfir said the table is already white (and in accordance with the design))
- [x] Notification - https://github.com/Tradeshift/tradeshift-ui/issues/511
- [x] Dialog - https://github.com/Tradeshift/tradeshift-ui/issues/518
- [x] Menu

**Comment by zdlm** [comment]
the table is already white (and in accordance with the design): http://ui.tradeshift.com/v12/#components/table/building.html
