### ISSUE TITLE
[Identity] New strategy for "second level tabs" and "root panels"

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#425]
1. Since the New Header () doesn't support second level tabs, we'll need to document how the New TabBox can be used to emulate this deprecated pattern at least until the app in question can become redesigned to comply with modern interface gudelines.

2. Since the minumum viable layout has changed, we'll also need to figure out how the top level tabs in the Header can be configured via HTML (for those that prefer this to JS configuration).

**Comment by lloydhumphreys** [comment]
@mihneaz can you create a graphic which shows the old pattern vs new pattern?
