### ISSUE TITLE
[Tabbar] Clickable active tab

### ISSUE THREAD

**Issue by nsp918** [Tradeshift/tradeshift-ui#427]
### Feature request
Clickable active tab
#### Description of feature
An active tab can be clicked again and it refreshes the page back to the default of that tab.
#### Example use cases and/or Prototype links
1, Within a tab you click on a selection (which loads into the same tab) and would like to get back to the start page of the tab /for example: table view -> view an element/
2, Look through a very long page then click it again to jump back to the top of the page by reloading it
#### Designs and/or Prototype screenshots
![active_tab](https://user-images.githubusercontent.com/15789426/32272746-be2ab8a2-beff-11e7-926b-0f04c32bc817.gif)

**Comment by bomouridsen** [comment]
Approved ✅

**Comment by nsp918** [comment]
@DocGroth Any update on this?
