### ISSUE TITLE
ChromeUI shows broken icons on Production

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#428]
ChromeUI shows broken icons on PRODUCTION

go.tradeshift.com
AND
ui.tradeshift.com

TSUI v9.2.4

![image](https://user-images.githubusercontent.com/22394106/32319130-07e6b292-bfec-11e7-8496-0fd096201cc4.png)

![image](https://user-images.githubusercontent.com/22394106/32319143-17703b84-bfec-11e7-9df0-bb856c13963e.png)

(check icons and especially search TRADESHIFT title)

**Comment by sampi** [comment]
Fixed in 9.3.2, released to production
