### ISSUE TITLE
TS MultiSelect form does not display correct number of selected items

### ISSUE THREAD

**Issue by cindyvandooren** [Tradeshift/tradeshift-ui#43]
Priority: medium (currently looking to see if I can find a way around this).

In the document profile generator v4 app, I'm using the multiselect form to set the languages for different document types. The different available languages are added to the form using ng-options. The selected languages are stored in an object, that keeps separate arrays for each document type. So in the select, I use either one of the arrays as the model (depending on the document type). 

```
<form data-ts="Form" name="languageForm">
    <fieldset>
        <label>
            <span>Select Needed Languages</span>
            <select multiple ng-model="selectedLanguages[selectedDocumentType.type]" ng-options="language.label for language in localeCodes" ng-change="setLanguages()"></select>
            <button ts-data="Button" class="ts-primary">
                <span>Set Languages</span>
            </button>
        </label>
    </fieldset>
</form>
```

I can successfully set the languages (I can see them showing up in the correct array), but when I'm switching between document types I see that the input in the form ("{number of selected items} selected") does not display the correct number of selected languages. 
An example:
The forms model is set to invoice and I set the languages English and Danish. selectedLanguages.invoice = [{English Language Object}, {Danish Language Object}]. The form correctly says that 2 languages have been selected. Then I switch to credit notes. The form's model is now selectedLanguages.creditnote = []. The form now says that 2 languages have been selected, but the model is empty. The form seems to remember the last value that was set. 

Including @TimeBomb in case he has something to add (since he helped me look into this issue)

**Comment by sampi** [comment]
Fixed in #628. Closing.
