### ISSUE TITLE
[Forms] Date input change not triggering on React > 15.6.1

### ISSUE THREAD

**Issue by romeldris** [Tradeshift/tradeshift-ui#435]
### Bug report
The onChange for date inputs do not work with React > 15.6.1. Currently Apps-Server is using 15.5.4 but if we do upgrade this is something that will break. 

I found this because I'm currently using React v16.0.0 on the cards-admin outside of Apps-Server. Will look at going back to 15.5.4 for now. 

Most likely related to these changes: https://reactjs.org/blog/2017/06/13/react-v15.6.0.html#improving-inputs

#### Tradeshift UI version affected
v9.3.2

#### Expected Behavior
The onChange is triggered for the input 
#### Actual Behavior
The onChange is not trigger for the input

#### Steps to reproduce
Select a date, should update the text field (to show the onChange)

React v15.5.4 (working)
https://codepen.io/anon/pen/BmQMpV

React v15.6.1 (not working)
https://codepen.io/anon/pen/wPoNGj

React v16.0.0 (not working)
https://codepen.io/anon/pen/RjovVL

**Comment by lloydhumphreys** [comment]
We'll take a look.

**Comment by zdlm** [comment]
This is a problem of React. They trigger the onChange event, when the input has an value. 
You can read it here https://github.com/facebook/react/issues/12061
We can't do anything in Tradeshift ui.
