### ISSUE TITLE
Table onselect not working for the first row

### ISSUE THREAD

**Issue by ciprianpratiats** [Tradeshift/tradeshift-ui#440]
### Bug report
In addition to this when clicking on the checkbox for the first row the onselect event is not triggering (all other rows seem to work fine)
#### Tradeshift UI version affected
v9.3.2
#### Expected Behavior
On ticking the checkbox to select the first row, onselect handler is triggered.
#### Actual Behavior
On ticking the checkbox to select the firs row, onselect handler is not triggered.
#### Steps to reproduce
Lookup the ProductCategorization in v4apps. It's main table is generated in this file: https://github.com/Tradeshift/Apps/blob/master/src/main/v4apps/apps/ProductCategorization/src/browser/components/ProductTableUI/ProductTableUI.js

**Comment by zdlm** [comment]
I tested this on our website, It works fine.
http://ui.tradeshift.com/#components/table/selecting.html
You can try to run `table.onselect = function(selected, unselected) {console.log(selected)};` ,
and check the console in the browser
