### ISSUE TITLE
[Tabbar] Does not re-render itself when going from ts-mobile to ts-tablet/ts-desktop

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#443]
[bug] TSUI v9.3.4, not related to browser type (at least Chrome at FF)

ui.Tabbar does not re-render itself while user changes browser width. Bug exists only in case if breakdown changes from `ts-mobile` to `ts-tablet/ts-desktop.` 

reproduced on http://ui.tradeshift.com/#components/forms/redesign.html

1. go to the page, 
2. set browser width less than 600px.  (to force ui components render mobile view)
3. Expand browser window bigger than 700px (ui components will render tablet view)
4. face empty tabbar

**Comment by DocGroth** [comment]
Fixed with https://github.com/Tradeshift/tradeshift-ui/pull/531
