### ISSUE TITLE
[React Spinner] TSUI does not remove Spinner overlay so can't interact with page

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#455]
I periodically facing weird spinner behavior on my React app:

I run spinner by setting `data-ts.blocking`. After I remove this attribute (or set it to empty string '' does not matter), grey overlay and spinner animation disappear, but i can't interact with the page.
The reason is that 
`<div data-ts-spirit="ts.ui.CoverSpirit" class="ts-cover ts-spinnercover ts-transition" id="ts-spinnercover"></div>`
blocks whole viewport. As shown above, it missing some classNames: `_gui-hidden _gui-invisible`

v9.3.8 and older

I can't make 100% repeatable case, but I face it every few page reloads. will update issue in case I will be able to make 100% working example

**Comment by ChuanTS** [comment]
I came across similar problem. Also in a React app, when call show-spinner and then call dismiss-spinner in very short delay, a div.ts-spinnercover will cover the whole page making it irresponsible.
