### ISSUE TITLE
Datepicker component does not disable the dates before the current one

### ISSUE THREAD

**Issue by mad-shift** [Tradeshift/tradeshift-ui#456]
#### Tradeshift UI version affected
v9.3.4.

#### Expected Behavior
Datepicker component should disable the dates before the current one when selecting a delivery date on an item card in Basket app

#### Actual Behavior
Datepicker component does not disable the dates before the current one when selecting a delivery date on an item card in Basket app - if the date was previously set to a year behind

#### Steps to reproduce
1. Add an item to basket that has delivery date one year behind (for example 2016)
2. Select that item and open datepicker component

#### Screenshots (optional)
![screenshot from 2017-11-24 10-24-33](https://user-images.githubusercontent.com/30900928/33214350-472a6012-d134-11e7-89b1-09d2a8cbec7a.png)
This is what happens when the year is 2012 for example
![screenshot from 2017-11-23 18-03-13](https://user-images.githubusercontent.com/30900928/33214351-474a8522-d134-11e7-87af-355889b7714b.png)
This is for the current year (expected behavior)
![screenshot from 2017-11-24 16-37-02](https://user-images.githubusercontent.com/30900928/33214724-c9660c74-d135-11e7-8ea4-1449f8854e13.png)

---------------------------

**Comment by wiredearp** [comment]
The `min` attribute must be specified using the same YYYY-MM-DD format as the `value` and that is not the case in your screenshot. Does it help if you try that?

**Comment by wiredearp** [comment]
:see_no_evil:
