### ISSUE TITLE
Shaky ESCAPE from Aside

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#468]
#### Tradeshift UI version affected
v9.3.11

#### Expected Behavior
The Aside should close on ESCAPE

#### Actual Behavior
It sometimes does, but at other times it needs multiple ESCAPE before it closes; and on OS X it appears to not  work at all or what ❓ 

#### Steps to reproduce
Open the Aside. Press ESCAPE. Behold the bug.

**Comment by DocGroth** [comment]
Fixed with https://github.com/Tradeshift/tradeshift-ui/pull/514
