### ISSUE TITLE
Time component labels are not translated

### ISSUE THREAD

**Issue by marinalecuts** [Tradeshift/tradeshift-ui#472]
#### Tradeshift UI version affected
v9.2.0

#### Expected Behavior
data-ts="Time" components should have translated labels, e.g. `1 year ago` should be translated to the user's language, as set in the User Settings.

#### Actual Behavior
data-ts="Time" components have English labels, regardless of the user's or the browser's language.

#### Steps to reproduce
Access User Settings and set a language other than English.
Access an app that uses `<time data-ts="Time"..../> tag. (e.g. Collaboration conversations with messages older than 1h).

#### Screenshots (optional)
See Time label:
![pasted image at 2017_10_26 07_16 pm](https://user-images.githubusercontent.com/28858004/33996770-e35ea13a-e0ea-11e7-9096-8e9f4627de1a.png)

**Comment by wiredearp** [comment]
🙈
