### ISSUE TITLE
[Tag] New Tag (& Label) component

### ISSUE THREAD

**Issue by sampi** [Tradeshift/tradeshift-ui#484]
#### Description of feature
Tags represent a set of interactive keywords that help label, organize, and categorize objects.

#### MVP features
* Static text
* Clickable text
* Removable
* Locked
* Colored

## Design
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/271828647/inspect)

![image](https://user-images.githubusercontent.com/24455813/35505497-94630934-04e6-11e8-8034-508728fdfc27.png)

**Comment by sampi** [comment]
The implementation supports the following parts:

* [Optional] Label
* Key/Value sets (value is optional; can have multiple keys and/or values)
* Delete icon
* Lock icon

From this, we should figure out the correct terms (my terms are not final, but this is how they are in the code, so if we change them, we should update the code as well so it stays clear for devs and designers):

* Label -> Key-only Tag (or we'll make it a `Label` component, which just uses a Tag behind the scenes)
* Value -> Label-only Tag
* Label-Value -> Key-Value

@bomouridsen can you also post more designs for the following?

* Maximized list of tags, AKA `Tags` component
* Multiple keys, multiple values
* Multiple sets of key-values

**Comment by bomouridsen** [comment]
@sampi Updated the design according to feedback.

#### Changes
- [ ] Smaller size, simelar to micro buttons (ts-unit)
- [ ] Text stayles for Label (Key) and value have switched 
- [ ] Added light varient (based on new color palette)

#### Things we need to figure out
- [ ] New size is to small for the figure, maybe match the button sizes. 2xUnit and a 1xUnit?

**Comment by jamessimo** [comment]
Is there any update on the progress of this issue @sampi

**Comment by wiredearp** [comment]
@jamessimo I don't think we can expect progress on any issue in the immediate future, so I would recommend not relying on Tradeshift UI for the implementation of tags if and when your need for this feature is immediate.
