### ISSUE TITLE
SEARCH input 

### ISSUE THREAD

**Issue by tcomboeanu** [Tradeshift/tradeshift-ui#489]
### Bug report
Having both `onseach` and `onidle` events on the Search input, When you click enter to trigger the search event, it also triggers the idle event.
#### Tradeshift UI version affected
v9.2.0

#### Expected Behavior
Should only call one event (`onsearch`) not both
#### Steps to reproduce
---------------------------

**Comment by tcomboeanu** [comment]
Hi @wiredearp, this bug is causing a lot of issues. Do you have an estimate?

**Comment by wiredearp** [comment]
@tcomboeanu I thought you found a workaround 😞 I’ll take a look at it tomorrow, but I’m not completely sure when it can be released (to V4), it will definitely not be tomorrow, so perhaps you can still attempt the temporary workaround: Wait an extra 50 milliseconds after one callback gets fired to see if the second one should also get fired (and potentially substract this amount of milliseconds from the `idletime`) in which case you cancel one of the other ensuing action.
