### ISSUE TITLE
[Icons] Need an icon `ts-icon-question` for Dialogs

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#49]
The standard purpose of the dialog is to as a question with options to `OK` and `Cancel`.

But we don't have a question mark icon and are currently using `ts-icon-todo` which really makes no sense at all. As a consequence, developers are forced to choose an alternative icon from the list, but then they face the same problem.

We must really get that icon in there.

**Comment by bomouridsen** [comment]
Fixed in #310
