### ISSUE TITLE
[CompanyCard] Encoded JSON and Embedded JSON not working in React+IE11

### ISSUE THREAD

**Issue by zdlm** [Tradeshift/tradeshift-ui#499]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
#### Tradeshift UI version affected
v9.2.0

#### Expected Behavior

Encoded JSON and Embedded JSON way of render Company card work on IE11

#### Actual Behavior
But not
#### Screenshots (optional)

---------------------------

**Comment by wiredearp** [comment]
But in that case, the first two CompanyCards on http://ui.tradeshift.com/#components/cards/companycard.html should not successfully render in IE11.

They do however render fine in IE11 (via Browserstack).

This text presented in this bug report is not very descriptive. Perhaps it is possible to elaborate further.

**Comment by zdlm** [comment]
`Encoded JSON` do not render in IE11. 
`Embedded JSON` could render in IE11 on our document web site. But It could not render on react

**Comment by wiredearp** [comment]
Well, then that's a problem with React, perhaps related to some kind of XSS prevention mechanism (which might be double-encoding the encoded value)? I'll change the issue title to reflect this and then we can discuss, whether or not we want to spend time on supporting this feature in React (given that there are other ways to provide data to the CompanyCard).

**Comment by sampi** [comment]
Fixed in https://github.com/Tradeshift/tradeshift-ui/releases/tag/v10.1.1
