### ISSUE TITLE
Pagination is not displayed correctly on mobile

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/tradeshift-ui#501]
### Bug report
Pagination is not displayed correctly on mobile when totalPages > 5.

#### Tradeshift UI version affected
v9.3.13

#### Expected Behavior
Pagination should be displayed correctly on mobile when totalPages > 5.

#### Actual Behavior
Pagination is not displayed correctly on mobile when totalPages > 5.

#### Steps to reproduce
Use pagination for totalPages > 5.

#### Screenshots (optional)
![pagination_mobile](https://user-images.githubusercontent.com/28289435/34947884-282e9fe4-fa14-11e7-9685-6b164f3a798d.png)

**Comment by wiredearp** [comment]
@MirelaPaun Hm 😕 The Table is supposed to reduce the number of page-buttons from 5 to 3 in the mobile breakpoint; and this also appears to work alright on the Docs website (for example in http://ui.tradeshift.com/#components/table/demo.html), so I am not sure exactly what went wrong. I assume that this footer is part of the Table (and not generated via the dedicated Footer API)? What are those strange dots near the top of the footer (between the footer and the Table body) ❓

**Comment by MirelaPaun** [comment]
I used Footer component  and Pager from Footer here. You can reproduce this issue here http://ui.tradeshift.com/#components/footer/pager.html.

**Comment by wiredearp** [comment]
Right. That is a bug. But anyways, the Table also comes with a built-in footer plus pager and this one does not have the problem. So unless you are using the Footer for other purposes, perhaps you can work around the bug by using the Table footer: http://ui.tradeshift.com/#components/table/paging.html

**Comment by MirelaPaun** [comment]
Thanks :+1:

**Comment by tynandebold** [comment]
Fixed in PR #526.
