### ISSUE TITLE
`onidle` is not called when clicking close button of search.

### ISSUE THREAD

**Issue by wangcansunking** [Tradeshift/tradeshift-ui#503]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
#### Tradeshift UI version affected
v9.3.11 v10

#### Expected Behavior
Here I use the search of toolbar as the expected behavior.
![image](https://user-images.githubusercontent.com/19563509/35264676-a1e44128-0058-11e8-93f5-f9631278519e.png)

#### Actual Behavior
![image](https://user-images.githubusercontent.com/19563509/35264642-83a81b08-0058-11e8-837a-81e4b0c7de50.png)

#### Steps to reproduce
```
var search = ts.ui.get('#mysearch');
search.value = 'Hello world';
search.onidle = function(value) {
	ts.ui.Notification.success(value);
};
```

#### Screenshots (optional)

---------------------------

**Comment by wiredearp** [comment]
... but `onsearch` is called; and also used as example in the documentation: http://ui.tradeshift.com/#components/search/. `onidle` is for when the user does nothing, whereas `onsearch` is for when the user does something (presses ENTER of clears the search).
