### ISSUE TITLE
[Footer] Missign designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#506]
#### P0
- [x] Collaboration action button should be blue
- [x] Acton bar background should be ts-slate-lightest with white text and actions, checkbox still blue.
- [x] Divider between toolbar-menu  (pagination) and ts-footerbar-backupbar (buttons)

#### P1
- [x] The Footer should have its own status message separate from the Actionbar. Should be in the left corner (old spot)

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276271712/inspect)

![image](https://user-images.githubusercontent.com/24455813/35564169-94b494d8-05b9-11e8-97ed-b184c887b088.png)

**Comment by wiredearp** [comment]
@bomouridsen We don't have any "blue" buttons no more 😬 Should this particular button simply be blue or are we looking to reintroduce blue as the secondary button color?

**Comment by lloydhumphreys** [comment]
todo: determine if this is still relevant given how Collab is always in the footer? @mihneaz

**Comment by zdlm** [comment]
The status is on the action bar, which I think is good. That space is for collaboration.
<img width="1153" alt="screenshot 2019-01-10 at 15 51 17" src="https://user-images.githubusercontent.com/6101287/50976474-59095080-14f0-11e9-9a11-9b2561660323.png">

**Comment by lloydhumphreys** [comment]
@zdlm how does this work when using the footer on a table? The dark bar looks a bit strong in that case I suppose.

**Comment by zdlm** [comment]
Like this:
<img width="352" alt="screenshot 2019-01-11 at 10 09 54" src="https://user-images.githubusercontent.com/6101287/51024183-15165a00-1589-11e9-8a61-cc89af83c465.png">

**Comment by lloydhumphreys** [comment]
@mihneaz Let's talk about this on Wednesday. I propose we ship it as-is and if we want to change the color in table-specific scenarios we do so in a future ticket.

**Comment by mihneaz** [comment]
@here 
I think it looks ok (I don’t want to change the color). 
Last week I tried to find out **if** we have any scenario with both status **and** action bar. I couldn’t find any so I think it’s ok to move forward as-is.

**Comment by tynandebold** [comment]
Closing this, since we're happy with how it is right now.
