### ISSUE TITLE
[Header] Missing designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#508]
#### P0
- [X] Add Settings & Support Action button API. Will float left of all other buttons.
- [x] The Header background should have a blue theme as an option. Default in TS apps.

#### P1
- [x] The Header background should have the option to be branded by a custom defined color.

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276078361/inspect)

![image](https://user-images.githubusercontent.com/24455813/35515754-424b9f98-050a-11e8-85e0-1cf9864700f3.png)

![image](https://user-images.githubusercontent.com/24455813/35515759-48c6fd4a-050a-11e8-8dad-f19adc6ffb1d.png)

**Comment by wiredearp** [comment]
TODO: Perhaps think about that "Support" icon for just a while longer. Perhaps a ❓ icon would come in handy.
