### ISSUE TITLE
[Search] Missing designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#509]
#### P0
- [x] Remove inner shadow
- [x] Implement same border color logic as our form inputs. Gray default, blue active etc.
- [x] Add "Clear" icon instead of a close icon. Should be slate-lightest color.

#### P1
- [x] Search icon should be ts-unit size.

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276069215/inspect)

![image](https://user-images.githubusercontent.com/24455813/35513906-cd3fbfe0-0504-11e8-9c25-54a257cb195c.png)

**Comment by tynandebold** [comment]
Completed TODOs with pull #711
