### ISSUE TITLE
[Note] Missing designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#510]
#### P0
- [x] The first examples seems broken
- [x] The text and icons should be custom color #7F7348 (Old @ts-yellow-text)
- [x] The dotted line is also #7F7348, but at 0.5 opacity.

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276067205/inspect)

![image](https://user-images.githubusercontent.com/24455813/35564225-bc7c8d04-05b9-11e8-929c-1639179b36e6.png)

**Comment by tynandebold** [comment]
Fixed with pull #714
