### ISSUE TITLE
[Notification] Missing designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#511]
#### P0
- [X] Use secondary buttons for Info, Warning and Danger notifications.

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276065568/inspect)

![image](https://user-images.githubusercontent.com/24455813/35513368-113a7e76-0503-11e8-8058-6137f0adde56.png)

**Comment by wiredearp** [comment]
TODO: Update that `error` icon 🍺

**Comment by tynandebold** [comment]
Updated that `error` icon in pull #713.
