### ISSUE TITLE
Value is empty and onidle will not called after copying content after clear.

### ISSUE THREAD

**Issue by wangcansunking** [Tradeshift/tradeshift-ui#562]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
#### Tradeshift UI version affected
v9.3.13

#### Expected Behavior
`onidle` and `onsearch` (entry `Enter`) will be called and the value is what is copied.

#### Actual Behavior
1. `onidle` is not called.
2. Press `Enter` the `onsearch` is called but the value is empty.

#### Steps to reproduce
1. code: 
```
var search = ts.ui.ToolBar.search();
search.value = 'Press ENTER here';
search.onidle = search.onsearch = function(value) {
	ts.ui.Notification.success(value || 'Search cleared');
};
```
2. copy specified content `test` in search input
3. click `clear` button
4. click search button and copy again
5. press `Enter` (optional, if we want to call `onsearch`)

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/19563509/37134633-5cd4f46c-22d4-11e8-9ead-a299cb59247b.png)

![image](https://user-images.githubusercontent.com/19563509/37134693-9b4e248e-22d4-11e8-86f8-5014873fb8a6.png)

---------------------------

**Comment by wangcansunking** [comment]
I find that it is because the `_snapshot` of `InputSpirit` and `SearchModel` is not updated after click `clear`.

**Comment by wiredearp** [comment]
That's exactly what happened! Sorry about the bug :grimacing: Thanks for digging in :beer:
