### ISSUE TITLE
[Channeling] Inline Spirits don't work with `data-ts`

### ISSUE THREAD

**Issue by sampi** [Tradeshift/tradeshift-ui#565]
#### Tradeshift UI version affected
v10.x

#### Expected Behavior
`<elem data-ts="my.custom.Spirit"/>` works
#### Actual Behavior
`<elem data-ts="my.custom.Spirit"/>` doesn't work

**Comment by wiredearp** [comment]
@dsp Can you :+1: https://github.com/Tradeshift/tradeshift-ui/pull/566 so we can close this?

**Comment by sampi** [comment]
Fixed in #566
