### ISSUE TITLE
Can't disable date format field

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/tradeshift-ui#57]
Current behavior: 
Disabled, readonly properties don't work for date field but text field.

Expected behavior: 
Disabled, readonly properties work for both date and text fields.

Steps to reproduce:
Make the following HTML by using TS UI components: 
```
<form ts-form> 
<fieldset> 
<label> 
<span>Disabled Text</span> 
<input type="text" disabled/> 
</label> 
</fieldset> 
<fieldset> 
<label> 
<span>Read-Only Text</span> 
<input type="text" readonly/> 
</label> 
</fieldset> 
<fieldset> 
<label> 
<span>Read-Only Date</span> 
<input type="date" readonly/> 
</label> 
</fieldset> 
<fieldset> 
<label> 
<span>Disabled Date</span> 
<input type="date" disabled/> 
</label> 
</fieldset> 
</form> 


```
Please also see the attached example.

We're building a 3rd party app for NOMURA and we have a plan to go live with the app at the end of this month. 

Please fix it asap.

**Comment by sampi** [comment]
Fixed. Closing.
