### ISSUE TITLE
Toggle the Sidebar UI Component is not working for the open call

### ISSUE THREAD

**Issue by kbrydges** [Tradeshift/tradeshift-ui#576]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
#### Tradeshift UI version affected
v9.2.0

#### Expected Behavior
GO is using the ts-topbar-menubutton in mobile to open a sidebar (code: ts.ui.get('#js-sidebar').open();). This is no longer working now that we updated the ui components. It is also not working in the example in ui.tradeshift.com:

see: http://ui.tradeshift.com/v10/#components/sidebars/
The Toggle Sidebar button:
var sidebar = gui.get('#mysidebar'); 
sidebar.open();

We have a very important demo with Apple for Tradeshift Go this Friday (3/23) and we will be unable to show them Tradeshift Go in mobile if the menu is broken. Help us!!!

#### Actual Behavior
The behavior is that this call is currently doing nothing, it should open the sidebar.

#### Steps to reproduce

Go to: http://ui.tradeshift.com/v10/#components/sidebars/
Select: Toggle Sidebar Button

#### Screenshots (optional)

---------------------------

**Comment by mihneaz** [comment]
Besides Go, this also occurs in other 3rd party apps: 
One Drive
Dropbox
Sharepoint Connector

![screen shot 2018-03-20 at 15 46 00](https://user-images.githubusercontent.com/510261/37662247-f1cf626a-2c56-11e8-8bf1-8180afc7d9d6.png)

**Comment by wiredearp** [comment]
@kbrydges You can try that with version `10.0.15`

**Comment by wiredearp** [comment]
@mihneaz This appears to be something going on witg the chrome. Can you make a new issue for that over on https://github.com/tradeshift/tradeshift-chrome/issues?

**Comment by kbrydges** [comment]
@wiredearp Thanks so much for the quick response on this! Tom was looking at this a bit too and came up with a workaround we can use in GO for this. The issue we see is in the following screenshot:

<img width="1905" alt="screen shot 2018-03-20 at 9 54 21 am" src="https://user-images.githubusercontent.com/3923808/37675654-02f86aba-2c33-11e8-934f-bd836841403a.png">

Since suspended is being set to true, the aside never opens. In the GO hack-we set this to false and then we see that the aside opens.

**Comment by kbrydges** [comment]
@wiredearp Actually-please disregard my previous message. We are seeing that the menu sidebar works in GO mobile when we upgrade to 10.0.15 (atleast locally). We are going to put this on the sales stack tomorrow and do more QA. Thanks for your quick response!

**Comment by wiredearp** [comment]
Awesome, sorry about the bug! The fix for the problem was actually quite funny: https://github.com/Tradeshift/tradeshift-ui/pull/577/files#diff-fa28a3c973117bdb41393d74e87637bbL168 :see_no_evil:
