### ISSUE TITLE
Tradeshift UI versus Angular 1.5

### ISSUE THREAD

**Issue by wiredearp** [Tradeshift/tradeshift-ui#586]
Inspired by this (Tradeshift internal) thread in Slack: https://tradeshift.slack.com/archives/C02TX8JJ7/p1522655604000193

1. UI components initialize as soon as the associated element gets appended to the page DOM.
2. It appears that Angular 1.5 now always compiles DOM structures in the page DOM, where before they did it in a detached DOM, inside a DocumentFragment, for performance reasons.
3. This causes some UI components to behave differently in Angular 1.5, so we will have to adapt.
4. The problem is know to affect (at least) the Switch in Forms.

The Angular guys probably did this for the same reason that we do it: Because a directive that needs information about the elements width or height or padding or margin (or just about any CSS property you can think of) requires for the element to be positioned in the DOM when you measure the property, or otherwise these lookups will return misleading values (such as zero for the width and height).

**Comment by n-srg** [comment]
Thank you, I can share my pr, where you can check what is going on https://github.com/Tradeshift/Apps/pull/7168
