### ISSUE TITLE
Lack of pagination on table.maximize(fn)

### ISSUE THREAD

**Issue by rafalages** [Tradeshift/tradeshift-ui#594]
### Bug report
@cchtradeshift @DocGroth 

#### Tradeshift UI version affected
v10.0.19

#### Expected Behavior
To have an automatically paginated table

#### Actual Behavior
It is showing all rows at once

#### Steps to reproduce
Have a table then maximize it passing a function as parameter

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/1014532/39233585-0ecc5446-4871-11e8-949c-d283d799dfa9.png)

**Comment by tynandebold** [comment]
The `maximize` method is deprecated. Instead, please use explode(optional_callback) to trigger the maximized layout and optimize() to trigger the automatic paging (that automatically updates on resize).
