### ISSUE TITLE
Page zooming breaks table cells

### ISSUE THREAD

**Issue by akarnachuk** [Tradeshift/tradeshift-ui#623]
----------------------------
#### Tradeshift UI version affected
v10.0.25

#### Expected Behavior
Vertical grid lines in table body should be aligned with header.

#### Actual Behavior
Table body cells and header cells have different width.

#### Steps to reproduce
Open demo table http://ui.tradeshift.com/v10/#components/table/demo.html fill it with data and change zoom in browser.

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/14124825/42089211-76b26b44-7bc6-11e8-943d-3dcf29d11d4b.png)

**Comment by zdlm** [comment]
Fixed in V12
