### ISSUE TITLE
[Docs] Searching on an iOS device will mess up zoom.

### ISSUE THREAD

**Issue by sampi** [Tradeshift/tradeshift-ui#631]
#### Tradeshift UI version affected
v10.*.*

#### Expected Behavior
* Zoom values should not change after searching

#### Actual Behavior
* Zoom values change after searching

#### Steps to reproduce
* Click on the Search icon in the top-left on the docs website.

**Comment by lloydhumphreys** [comment]
- [ ] Add a meta tag so that the zoom is disabled on mobile

**Comment by mihneaz** [comment]
![img_2640](https://user-images.githubusercontent.com/510261/51181397-5aa98e80-18cb-11e9-8cb2-42258abe6965.JPG)
![img_2641](https://user-images.githubusercontent.com/510261/51181399-5c735200-18cb-11e9-8a2e-5f441b53db80.JPG)

**Comment by DocGroth** [comment]
Will not fix this
