### ISSUE TITLE
[Docs] versions.html uses String.prototype.includes()

### ISSUE THREAD

**Issue by sampi** [Tradeshift/tradeshift-ui#666]
**Describe the bug**
IE11 throws an error because the version dropdown uses `String.prototype.includes()` which is not supported.

**To reproduce**
Try to load http://ui.tradeshift.com in IE11

**Expected behavior**
The docs should load.

**Desktop (please complete the following information):**
 - OS: Win7/11
 - Browser: IE
 - Version: 11

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by tynandebold** [comment]
Fixed with pull #670
