### ISSUE TITLE
Modal footer is not hidden when removing the buttons

### ISSUE THREAD

**Issue by bogdan-brezuica** [Tradeshift/tradeshift-ui#700]
**Describe the bug**
The modal footer is not hidden automatically after removing the buttons.

**To reproduce**
Remove modal buttons. The empty footer will still be visible

**Expected behavior**
The footer should be hidden when it is empty

**Framework usage**
React v16.6

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 71.0.3578.80

ts-ui version 11.1.0

**Comment by DocGroth** [comment]
@bogdan-brezuica I'm a little curious of the scenario where we would have a button and then remove it. Would we not disable it instead?

**Comment by bogdan-brezuica** [comment]
When I found this behaviour I was trying to use the same modal element for different "pages". You can imagine having a modal with multiple steps, so when the step changes, the modal content changes (including the footer buttons). Probably not the best way to use the modal component though, so I found a workaround for it

**Comment by lloydhumphreys** [comment]
- [ ] Investigate if there's a footer hide for modals
- [ ] Add one if there isn't
- [ ] Document it

**Comment by zdlm** [comment]
You can use `modal.footer().clear();` to do it.
