### ISSUE TITLE
Switching versions in documentation might lead you to a 404 page with no navigation

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/tradeshift-ui#722]
**Describe the bug**
Example: I'm on this page in the documentation:
http://ui.tradeshift.com/v12/#components/header/tabs.html
I switch to version 11 and I get a 404 page with no navigation

**To reproduce**
Example: I'm on this page in the documentation:
http://ui.tradeshift.com/v12/#components/header/tabs.html
I switch to version 11 and I get a 404 page with no navigation

**Expected behavior**
Example: I'm on this page in the documentation:
http://ui.tradeshift.com/v12/#components/header/tabs.html
I switch to version 11 and I should to the front page (or maybe you have a better suggestion :-) )

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: 12 going to 11 or 10

**Comment by zdlm** [comment]
Because we don't have `header` (new features only in v12 ) in v11 and v10.
