### ISSUE TITLE
onselect method for buttons on boards does not work. 

### ISSUE THREAD

**Issue by shashank1010** [Tradeshift/tradeshift-ui#756]
**Describe the bug**
The onselect method defined for a button that was passed as an object to a board does not work.

**Expected behavior**
The buttons section in the documentation adds the buttons to the header of the board. 
On clicking **Three**, the notification should be displayed.

**Framework usage**
 React v16.5.0, however, this is reproducible on the documentation page as well

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 72.0.3626.109

**Additional context**
This is my first time using the library. Tried to understand what the issue could be. But it doesn't help.
Tried changing the name from **onselect** to **click** and **onclick**, but that breaks the program.

**Comment by shashank1010** [comment]
On further analysing the reference link, i figured I'll have to configure it using the forEach method on the buttons method for boards.

While the solution to get the click functionality working is a part of the Header API, the onselect method in the boards documentation page is incompletely documented. I believe, just by demonstrating how to binding to the click event (since we have the onselect mentioned there) for each button in Boards documentation page as well will probably make the work of a newbie for Tradeshift UI a little more easier.

If required, I could create a pull request for the same as it is not a lot of work and the fix is required only in the docs.

**Comment by zdlm** [comment]
Sorry for confusing use. It is our mistake. It should be `onclick`. I will update the document.
