### ISSUE TITLE
[Table] Select text will trigger click event and pass incorrect rowIndex/cellIndex

### ISSUE THREAD

**Issue by ding-js** [Tradeshift/tradeshift-ui#768]
**Version**
tradeshift-ui 12.2.0

**Describe the bug**
Select text will trigger click event and pass incorrect rowIndex/cellIndex

**To reproduce**
http://ui.tradeshift.com/v12/#components/table/clicking.html
Select text cross more than two rows of the table
![tradeshitf-ui](https://user-images.githubusercontent.com/14885918/54663962-df0fcc00-4b1d-11e9-81c7-13e7e75f8872.gif)

**Expected behavior**
Don't trigger click event.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Version: 72.0.3626.121

**Comment by DocGroth** [comment]
We will fix this by only taking action when the MouseUp occurs in the same field as the MouseDown

**Comment by ding-js** [comment]
> We will fix this by only taking action when the MouseUp occurs in the same field as the MouseDown

@DocGroth 

Why not use 'click' instead of 'mousedown & mouseup'? It has some difference with browser effect.
