### ISSUE TITLE
[DatePicker] Extend date-picker with ability to deselect, defaults

### ISSUE THREAD

**Issue by lloydhumphreys** [Tradeshift/tradeshift-ui#777]
Currently, it's not possible to _deselect_ a chosen date from within the date-picker. We should add a button that allows that.

It's also been requested that we add a `note` field to the top of the date-picker, which I hope we can all agree would be useful!

It's also necessary to manually select every date - perhaps we should extend the component with some sensible defaults. For example: in 7 days, in 30 days, 90 days... etc

- [x] @mihneaz design
- [ ] Note with instructions at the top of the aside
- [ ] Deselection
- [ ] Sensible defaults

**Comment by mihneaz** [comment]
Deselect and note component" 
![Datepicker](https://user-images.githubusercontent.com/510261/56018150-981e8c00-5d01-11e9-970c-80c3974bdef6.png)
