### ISSUE TITLE
[Spinner] Spinner is not covering footer nor header

### ISSUE THREAD

**Issue by Loredana-Noata** [Tradeshift/tradeshift-ui#778]
**Describe the bug**
In UI12, the spinner when is not active create an extra space in the bottom of the page. 
When is active, is visible in the bottom - is covering only half of the layout. 
When adding new property in our css (position: absolute) is not covering the footer nor header. 

**To reproduce**
See attached images. 

**Expected behavior**
When active, spinner should cover the whole page

**Framework usage**
React 16.8.3

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Chrome 
 - Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
-not tested yet

**Additional context**
-
<img width="1664" alt="spinner_" src="https://user-images.githubusercontent.com/48242633/56036672-1a28a800-5d36-11e9-8708-28a9b6023638.png">
<img width="1678" alt="spinner_ui11" src="https://user-images.githubusercontent.com/48242633/56036673-1a28a800-5d36-11e9-9652-7fdd08e6533e.png">
<img width="837" alt="spinnerUI12" src="https://user-images.githubusercontent.com/48242633/56036674-1a28a800-5d36-11e9-80c4-40566bc2238d.png">

**Comment by zdlm** [comment]
We changed the layout in V12. 
You can use new method to make a full page spinner 
```
ts.ui.get('.ts-app', function(app) {
	app.blocking('Chrunching data');
	setTimeout(function() {
		app.done();
	}, 1500);
});
```
The link is here http://ui.tradeshift.com/v12/#components/spinners/
