### ISSUE TITLE
[Modal] Update modal to have a mode which is not entirely full-screen

### ISSUE THREAD

**Issue by lloydhumphreys** [Tradeshift/tradeshift-ui#783]
Currently, the modal takes up the whole screen. There are some pro's and cons..

Pros: fully captures your attention, good for wizards
Cons: no contextual info about what you're doing, quite "committal" in terms of what you're doing.

--

Proposal from discussions with Geoff and Mihnea. Designs incoming for all.

- [x] A - Take the full screen modal and inset it by default (1)
- [x] B - Add a property to the modal that allows it to be inset by a lot (2)
- [x] C - On mobile, (A) stays as it is today (full screen, no fancy stuff)
- [ ] D - On mobile, (b) changes a bit - bump the start of the modal down and allow you to "scroll" to expand if there's enough content (3) - take Google Maps on mobile as an example, the search/content stuff is stored in this swipe-up menu that I think we could embrace.

![2019-05-08 at 14 47](https://user-images.githubusercontent.com/1584500/57376446-49e59700-71a0-11e9-92d8-05e72c4c35d2.png)

![2019-05-08 at 14 53](https://user-images.githubusercontent.com/1584500/57376780-27a04900-71a1-11e9-86d8-f0005daac6aa.png)

![2019-05-08 at 14 55](https://user-images.githubusercontent.com/1584500/57376963-8ebdfd80-71a1-11e9-914f-94e60139e708.png)

**Comment by mihneaz** [comment]
Here is the design for the modal with a small inset (A). Please note this is already used by designers. 
![Future](https://user-images.githubusercontent.com/510261/61289114-ddeb6480-a7c8-11e9-8666-cadd0c0c18a8.png)
Abstract link: https://share.goabstract.com/9de83bce-25f8-46f9-b036-cb1b9463bb72?mode=design&sha=de22a3e54752d2b58f987e4e8f427f3f2d78ff68

**Comment by mihneaz** [comment]
#### C - On mobile, (A) stays as it is today (full screen, no fancy stuff)
![Mobile-D](https://user-images.githubusercontent.com/510261/61379889-b4096f00-a8a8-11e9-9100-25fbc6673c56.png)

**Comment by esmailpour-hosein** [comment]
@mihneaz The backdrop (cover) color is different from the cover spirit which is used for `Aside` and `Dialog`. For cover spirit it's `rgba(0,0,0,.71)`. Sorry if the names are misleading 😅

**Comment by mihneaz** [comment]
@esmailpour-hosein hmm, let's keep the current cover spirit: `rgba(0,0,0,.71)`. Thanks for pointing it out, I will change it in our design files. 

Here is the design for **B - Add a property to the modal that allows it to be inset by a lot (2)**
![Small](https://user-images.githubusercontent.com/510261/61795549-f93b1d00-ae23-11e9-9252-04f951a88748.png)

Abstract link: https://share.goabstract.com/4641ab75-9c4f-4866-b2f2-7c76961b3cca?mode=design&sha=a61da196c38ebf8d0c9946bdffb2cef75eaaaa11

**Comment by zdlm** [comment]
This is make the developer confuse, how to choose aside or modal like this. I think you need to talk to @jerf first.
