### ISSUE TITLE
Add support for showing and hiding toolbar in Footer

### ISSUE THREAD

**Issue by najafsen** [Tradeshift/tradeshift-ui#799]
I need to show and hide the `toolbar` in `ts.ui.Footer` conditionally. Currently, when I add a `checkbox` to `Footer`, it shows up the `toolbar`, but when I hide the `checkbox`, the `toolbar` does not disappear. I think it would be good to have `showToolbar` and `hideToolbar` functions in `ts.ui.Footer`.
You can read the full conversation about this [here](https://tradeshift.slack.com/archives/C02TX8JJ7/p1558524736015000).

**Comment by muwenzi** [comment]
I cannot find function likes `hide()` to hide `ts.ui.Header`

And I use these code temporarily: 
```js
ts.ui.Header.show = () => {
	const element = document.getElementsByClassName('ts-headerbar')[0];
	if (element) {
		element.style.display = 'block';
	}
};

ts.ui.Header.hide = () => {
	const element = document.getElementsByClassName('ts-headerbar')[0];
	if (element) {
		element.style.display = 'none';
	}
};
```
