### ISSUE TITLE
Some kind of workshop for developer outreach

### ISSUE THREAD

**Issue by lloydhumphreys** [Tradeshift/tradeshift-ui#81]
Teams have significantly different priorities to the TSUI team, and let's face it, you guys will never be able to build things exactly when we need them. That's not a criticism - our goals just don't always align, and stuff gets pushed out. That's fine.

In light of that, can we do some kind of workshop, to help frontend devs understand how they can contribute to the components? Then we can hopefully increase velocity, and instead of requesting changes, we can be submitting PRs. Spread out the ownership, so that developers have a vested interest in making TSUI efforts successful.

**Comment by sampi** [comment]
@lloydhumphreys I gave a short talk on how ts.ui works and how you can use it to build a small component, with code examples.

It's available here: https://opbeat.com/community/posts/fake-your-webcomponents-by-daniel-spitzer/

**Comment by sampi** [comment]
there will be a workshop in november, we'll collect all the slides and exercises from it.
