### ISSUE TITLE
[Modal+Dialog] Pressing ESC renders the Dialog twice upon closing the Modal

### ISSUE THREAD

**Issue by yeetrium** [Tradeshift/tradeshift-ui#812]
**Describe the bug**
Pressing ESC renders the Dialog twice upon closing the Modal. If a TSUI dialog is placed on top of a modal and the ESC key is pressed, the dialog renders twice each time the ESC key is pressed after confirming to close the modal.

**To reproduce**
Insert the following code on Example 2 named [Modal Buttons](http://ui.tradeshift.com/v12/#components/modals/):
```
ts.ui.get('#example2', function(modal) {
	modal.buttons([{
		label: 'Close the Modal',
		type: 'ts-primary',
		onclick: function() {
			modal.close();
		}
	}]).open();
});

ts.ui.get('#example2', function(modal) {
	Object.assign(modal, {
		onclose: () => {
			ts.ui.Dialog.confirm(
				'There are unsaved changes, do you want to save and exit?',
				'Save and Exit',
				'Exit without Saving',
				{
					onaccept: () => true,
					oncancel: () => true
				}
			);
			return false;
		}
	});
});
```

**Expected behavior**
The Dialog box should only appear once after pressing the ESC key on the Modal.

**Framework usage**
React v16.8.0

**Desktop (please complete the following information):**
 - OS: MAC/WIN
 - Browser: Chrome, Firefox, Safari, Opera
 - Version: Latest versions

**Smartphone (please complete the following information):**
 - Device: LG
 - OS: Android Q
 - Browser: Chrome
 - Version: Latest

**Additional context**
Check this video out to see the issue in action:

![modal_esc_bug_dialog](https://user-images.githubusercontent.com/9067473/59138765-af65a880-8943-11e9-8830-594ed1c4d81a.gif)

**Comment by yeetrium** [comment]
Hi @zdlm I tested the change and it works upon closing the modal, but when pressing escape on the dialog box, the same behavior occurs. Please add the fix to the dialog box as well.

**Comment by zdlm** [comment]
Hi @yeetrium . Thanks for reporting. 
But the dialog has the code to avoid escape twice. 
https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/core/core-gui@tradeshift.com/spirits/dialogs/ts.ui.DialogSpirit.js#L200
Can you make a video as well .  Thanks

**Comment by yeetrium** [comment]
Hi @zdlm here's the new video for the dialog escape bug:
![dialog_box_esc_bug](https://user-images.githubusercontent.com/9067473/60628990-c2d02c00-9da8-11e9-9016-84dcbad8d551.gif)


Let me know if there are any questions.

**Comment by zdlm** [comment]
You know, the previous problem is the Model trigger twice `onclose` when we press `ESC`. So the it generate two dialogs. I fixed the but in the Model. But the dialog should be all right. 

In the video, it seems the same things happen again. Which is also because of the Model.
Are you sure you are using the latest version of tradeshift-ui. The latest version is 12.2.9

**Comment by yeetrium** [comment]
Hi @zdlm, in the beginning of the video I provided screen grab of the git changes I made locally in fintech-apps. I updated tradeshift UI to 12.2.9

<img width="1398" alt="Screen Shot 2019-07-05 at 11 01 34 AM" src="https://user-images.githubusercontent.com/9067473/60738785-5ffba380-9f14-11e9-8010-6605fb53fa26.png">

I pressed escape on the dialog and the issue occurred.

It may be an issue with mixing the two components. Please let me know if any additional info is needed.

**Comment by zdlm** [comment]
Can you help me to debug. Put a console.log('something') in to  the event of the model `onclose and onclosed`
```
ts.ui.get(myelement, modal => {
	Object.assign(modal, {
		onopen: () => console.log('Will open'),
		onopened: () => console.log('Did open'),
		onclose: () => console.log('Will close'),
		onclosed: () => console.log('Did close')
	});
});
```
Check how many times does it been called.

**Comment by zdlm** [comment]
Or  can you make some demo code on https://jsfiddle.net/ , that I can reproduce. That would be really helpful.

**Comment by yeetrium** [comment]
Hi @zdlm I made some demo code here:
https://jsfiddle.net/30Lgomt4/2/

Press esc after clicking the button to close the modal and observe that the dialog opens again. It should close. So the esc button for the modal should be ignored while the dialog popup box is shown.
