### ISSUE TITLE
[Table] Sort function should ignore spaces preceding the value

### ISSUE THREAD

**Issue by zdlm** [Tradeshift/tradeshift-ui#825]
**Describe the bug**
The item with space is always ranked first, even if the first real-character is not.

**To reproduce**
Sort with space items

**Expected behavior**
Trim the space value

**Framework usage**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by esmailpour-hosein** [comment]
Is this our issue or other developers need to trim their data when they want this?
No sure if in this way we are changing the expected behaviour or not! Is there any case that there should be space at first of the value?
