### ISSUE TITLE
Button color on header depends on header color

### ISSUE THREAD

**Issue by DvornikovSergey** [Tradeshift/tradeshift-ui#826]
**Describe the bug**
The color of the buttons (`ts-secondary` and `ts-tertiary`) depends on the color of the header
![image](https://user-images.githubusercontent.com/15032696/60880363-bd258b00-a26d-11e9-861e-b1e2d18c8943.png)

**Expected behavior**
They are expected to be white

**Framework usage**
angular js 1.5.11

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Browser: Chrome 75.0.3770.100

**Comment by lloydhumphreys** [comment]
Is this the exact design you're attempting to achieve?

The buttons are designed to adapt to the background - in this case, perhaps they should be white as they look disabled - but ultimately, the problem here lies with the black header. I don't believe this is something we're continuing to support design wise (the library supports it for legacy reasons).

cc @jerf @mihneaz can you weigh in?

**Comment by DvornikovSergey** [comment]
First of all, this is just an example. Specifically, I'm interested in `blue header` + `white button`

**Comment by lloydhumphreys** [comment]
Can you share the Blue version with us, so we can see what you mean?

Ideally you should be saying `blue header` + `buttons` and the header handles the styling so that it's consistent.

**Comment by DvornikovSergey** [comment]
![image](https://user-images.githubusercontent.com/15032696/60809991-3c578800-a1b6-11e9-9aa3-429f1c700980.png)

This button is `ts-tertiary`

**Comment by jerf** [comment]
My question here is about this being a `ts-tertiary` button - this is the Primary action for the page right? It should be a primary button?

@DvornikovSergey who is the designer providing this? Ioan? Stefan?

**Comment by DvornikovSergey** [comment]
Ioan

**Comment by xionatan** [comment]
@DvornikovSergey the button should be WHITE background... :)
Also, something is strange in this screen... the app name is called SHOP MANAGER but the action for the button is "CREATE COLLECTION", so... they are 2 different things!

**Comment by DvornikovSergey** [comment]
@xionatan, 

> the button should be WHITE background

No, need `white button` on `blue header `

> something is strange in this screen... the app name is called SHOP MANAGER but the action for the button is "CREATE COLLECTION", so... they are 2 different things!

This is correct app and design

**Comment by xionatan** [comment]
If it's VIEW MANAGER it's correct, but if it's SHOP MANAGER... it's not!
Also, yes... like also @lloydhumphreys and @jerf said, the color of the button should be WHITE.

**Comment by DvornikovSergey** [comment]
Please do not argue with me about the name of the application. This application was created exactly as a Shop Manager and there are plans to add some more functionality that is not related to collections.

If you want to argue about this, talk to Elizabeth better.

**Comment by xionatan** [comment]
I'm not arguing :) sorry if you misunderstood it like that.
I know exactly what SHOP MANAGER is... and it should have COLLECTIONS / VIEW MANAGER and MARKETPLACE CONFIGURATION as sub-sections (tabs).

I'll take it with Elisabeth for more details, but... just that you are aware of this :)

**Comment by DvornikovSergey** [comment]
I know that there should be tabs, since so far there is only one functional, I was asked to hide the tabs altogether

**Comment by xionatan** [comment]
I understand, but in the context of this being pushed to production, the app name beeing called SHOP MANAGER and everything else is regarding COLLECTIONS... it will be "a little funny" for the end-user! :)
