### ISSUE TITLE
Modal window is not full screen

### ISSUE THREAD

**Issue by DvornikovSergey** [Tradeshift/tradeshift-ui#827]
**Is your feature request related to a problem? Please describe.**
I would like to be able to open the modal window as shown below
![image](https://user-images.githubusercontent.com/15032696/60880848-a7649580-a26e-11e9-932d-e2201c0e5f0d.png)
i.e. with paddings

**Describe alternatives you've considered**
Alternatively, your suggestion of how this can be achieved with the help of additional layout / styles

**Comment by lloydhumphreys** [comment]
Closing - see #783
