### ISSUE TITLE
Board with subtitle

### ISSUE THREAD

**Issue by DvornikovSergey** [Tradeshift/tradeshift-ui#828]
**Is your feature request related to a problem? Please describe.**
I would like the subtitle (or comment) to be shown in `Board`, as shown below
![image](https://user-images.githubusercontent.com/15032696/60880848-a7649580-a26e-11e9-932d-e2201c0e5f0d.png)

**Describe alternatives you've considered**
An alternative may be your suggestions on how this can be implemented in current realities.

**Comment by lloydhumphreys** [comment]
I'm not sure I understand the request. Like "Filters" and the sub-text?

The board is just a container, and within it is a _Panel_. You can put stuff in there and format it however you'd like: http://ui.tradeshift.com/v12/#components/boards/

**Comment by DvornikovSergey** [comment]
> I'm not sure I understand the request. Like "Filters" and the sub-text?

Yes

**Comment by DvornikovSergey** [comment]
> The board is just a container, and within it is a _Panel_. You can put stuff in there and format it however you'd like: http://ui.tradeshift.com/v12/#components/boards/

This is exactly what I wouldn’t want to do, since I don’t have any idea how much it will crawl if I add a control element (button, switch, etc.)

I would like to have a similar opportunity out of the box just to call:
```&js
ts.ui.get('#board', function(board) {
	board
		.title('My Board')
		.subtitle('Sub title')
		.buttons(...);
});
```

**Comment by lloydhumphreys** [comment]
> I don’t have any idea how much it will crawl

What is _crawl_?

**Comment by zdlm** [comment]
You can make a `div` container and put a title and subtitle and a button. Set some css, it is easy to achieve the design.

**Comment by DvornikovSergey** [comment]
Well, when I come to this, I will try to do it with css
