### ISSUE TITLE
[aside] Aside panel duplicates tab model

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#837]
**Describe the bug**
Aside panel does not clear tab model while element getting moved to another place.
Typical example: We define aside in some place and wrap it into some framework-specific component. This component moves DOM element outside the `Main` container

![image](https://user-images.githubusercontent.com/22394106/61865399-5ce54900-aefd-11e9-8224-e9b15c909b58.png)

**To reproduce**
What this example does is:
1. Aside panel shows up and renders correctly
2. Panel closes, and Javascript moves it into some container
3. Panel opens again, and you can see duplicates in tabs
https://jsfiddle.net/Lh7o0fx8/6/

**Expected behavior**
In both cases aside panel should contain 2 tabs [tab 1, tab2]

**Framework usage**
there is no framework involved

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Latest

**Additional context**
I believe it is not related to any specific environment.
Code example copy-pasted from ui.tradeshift.com

**Comment by zdlm** [comment]
I checked your demo https://jsfiddle.net/Lh7o0fx8/6/ 
You are not moving all the aside to somewhere. you just `panels.append(panel);`. That means you append two panels. That's if why you got two more. 
I think may want to do `panels. removeChild(panel)`
