### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by DvornikovSergey** [Tradeshift/tradeshift-ui#847]
**Describe the solution you'd like**
I don’t know, maybe it was already suggested, I didn’t find it, but it would be very good if you added typescript definitions for UI-Components API 👍

**Comment by n-srg** [comment]
we can create `@types/tradeshift-ui` package as other vendors do and fullfill it easily. @DvornikovSergey we can start

**Comment by n-srg** [comment]
it will not break any code until we will add it in `tsconfig.json` as types definition
