### ISSUE TITLE
[Board] Does not clear tab header when I want to

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#859]
**Describe the bug**
Board components keeps empty tab header when there was some tabs on it and I asked to clear tabs at all

**To reproduce**
https://jsfiddle.net/k2wa3vhq/

**Current behavior**
Take a look on the board - you can see ampty tabs container appears. It stays also if I call `.clear()`

**Expected behavior**
Tab container should be removed when I set `board.tabs([])` and should be removed for sure 
when I call `board.tabs().clear()`

**Framework usage**
Vanilla JS

**Comment by zdlm** [comment]
It is hard for us to know there is nothing in the header. 
It could be easier for developers to hide the header when it is empty.
You can do like:
```
ts.ui.get('#board', function(board) {
	board._head(). visible = false; // set it to true to show it.
});
```

**Comment by n-srg** [comment]
yeah, sound good. work as expected. thanks for workaround! :beer:
