### ISSUE TITLE
[Notification] Ability to trigger a followup callback after notification goes away

### ISSUE THREAD

**Issue by RimanDk** [Tradeshift/tradeshift-ui#879]
**Is your feature request related to a problem? Please describe.**
Right now we have multiple places in which we trigger `ts.ui.Notification.success` and manually time with a `setTimeout(()=>{...}, 3000)` to execute redirects or similar after it fades away.

**Describe the solution you'd like**
It would be nice to get an extra parameter a la `onFade` on the `.success` notification, which you guys will trigger after your own internal timeout ends. This way, if you change the timeout, we won't have to update everywhere in our product as well.

**Describe alternatives you've considered**
Let `ts.ui.Notification.success` return a `Promise`, which is resolved, when the panel is done fading out.

**Additional context**
None

**Comment by zdlm** [comment]
Hi,@RimanDk . You can do this: 
```
ts.ui.Notification.success('You did it!',{
onclosed:function(){
console.log("Put your code here.")
}
});
```
We have `onclose and onclosed` which you want. We have `open and opened` as well.

We miss the documentation. I will write more in document about the events.
