### ISSUE TITLE
[modal] ts-micro Applies for whole modal content

### ISSUE THREAD

**Issue by n-srg** [Tradeshift/tradeshift-ui#886]
**Describe the bug**
defining the modal with `class="ts-micro"` applies micro-style for all ui-elements inside modal window

**To reproduce**
- Open http://ui.tradeshift.com/v12/#components/modals/
- Find the _Micro Size_ section
- launch modal in that section
- catch ui-button on the modal is at micro size

**Expected behavior**
Expect to see micro-style only for modal itself i.e. extra padding plus small header, but elements in the modal content to be usual size (normal)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Version: latest
 - TSUI 12.3.3

**Additional context**
Take a look on screenshot: there is the button on the modal. But it is defined as `ts-primary`, no `ts-micro` class on it. It still being rendered as micro-button

<img width="1172" alt="Screen Shot 2019-11-04 at 20 24 59" src="https://user-images.githubusercontent.com/22394106/68124156-3e9dd900-ff41-11e9-92af-414a7d741bfb.png">

**Comment by andrenicodemus** [comment]
Could we make sure that the close ( X ) icon is also not getting the ts-micro styling? 

![image](https://user-images.githubusercontent.com/1531615/68128889-dfc46980-ff18-11e9-9f95-2e9e2cda348d.png)
