### ISSUE TITLE
[Table] Add opportunity to disable/enable markdown support

### ISSUE THREAD

**Issue by irinaklimova** [Tradeshift/tradeshift-ui#964]
**Is your feature request related to a problem? Please describe.**
For now we have markdown by default in tables (https://ui.tradeshift.com/v12/#components/table/formatting.html), but for some cases we need to display text without markdown (for example, product names).

![Снимок экрана 2020-10-09 в 173004](https://user-images.githubusercontent.com/5559097/95596065-1daa0600-0a77-11eb-81c5-c0784a1e957d.jpg)
![Снимок экрана 2020-10-09 в 173022](https://user-images.githubusercontent.com/5559097/95596074-213d8d00-0a77-11eb-8e33-3188d7e402bc.jpg)

**Describe the solution you'd like**
It can be new method for togging markdown support in selected table.

**Comment by ehats** [comment]
Piggybacking on this to say that this has led to multiple security issues so far and having to manually escape markdown everywhere just doesn't work very well.

Ideally markdown support should be an opt-in feature, although I do realise that that would be a breaking change. Still, please consider that for future components
